# Generated by Django 4.0 on 2021-12-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=200)),
                ('nome_fila', models.CharField(max_length=200)),
                ('vaga', models.CharField(max_length=200)),
                ('site', models.CharField(max_length=200)),
            ],
        ),
    ]
