# Generated by Django 4.0 on 2021-12-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filadigital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fila',
            name='status',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
