# Generated by Django 4.0 on 2021-12-10 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fila', '0001_initial'),
        ('ordemfila', '0002_alter_ordem_fila_vaga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem_fila',
            name='fila',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ordem_fila',
            name='vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fila.vaga_fila'),
        ),
    ]
