# Generated by Django 4.0 on 2021-12-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemfila', '0003_alter_ordem_fila_fila_alter_ordem_fila_vaga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem_fila',
            name='vaga',
            field=models.CharField(max_length=200),
        ),
    ]
