# Generated by Django 4.0 on 2021-12-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemfila', '0004_alter_ordem_fila_vaga'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem_fila',
            name='posicao2',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
