# Generated by Django 4.0 on 2021-12-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemfila', '0005_ordem_fila_posicao2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem_fila',
            name='posicao2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
