# Generated by Django 4.0 on 2021-12-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemfila', '0006_alter_ordem_fila_posicao2'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem_fila',
            name='posicao3',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
