# Generated by Django 4.0 on 2021-12-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemfila', '0007_ordem_fila_posicao3'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem_fila',
            name='placa',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
